image: haskell:8.6.3

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

stages:
  - test

ghc-8.6.3:
  stage: test
  script:
    - stack test --fast --system-ghc
