image: haskell:8.2.2

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work
    - target

stages:
  - build
  - test

build:
  stage: build
  script:
    - stack build

unit-test:
  stage: test
  script:
    - stack test
