name: versions
version: '3.3.2'
synopsis: Types and parsers for software version numbers.
description: 'A library for parsing and comparing software version numbers.
             We like to give version numbers to our software in a myriad of
             ways. Some ways follow strict guidelines for incrementing and comparison.
             Some follow conventional wisdom and are generally self-consistent.
             Some are just plain asinine. This library provides a means of parsing
             and comparing /any/ style of versioning, be it a nice Semantic Version
             like this:


             > 1.2.3-r1+git123


             ...or a monstrosity like this:


             > 2:10.2+0.0093r3+1-1


             Please switch to <http://semver.org Semantic Versioning> if you
             aren''t currently using it. It provides consistency in version
             incrementing and has the best constraints on comparisons.'

category: Data
author: Colin Woodbury
maintainer: colin@fosskers.ca
license: BSD3
homepage: https://gitlab.com/fosskers/versions

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -Wincomplete-uni-patterns

dependencies:
  - base >= 4.8 && < 4.12
  - megaparsec >= 6 && < 7
  - text >= 1.2 && < 1.3

library:
  exposed-modules:
    - Data.Versions
  other-modules: []
  dependencies:
    - deepseq >= 1.4 && < 1.5
    - hashable >= 1.2 && < 1.3

tests:
  versions-test:
    main: Test.hs
    source-dirs: test
    other-modules: []
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - base-prelude
      - checkers >= 0.4 && < 0.5
      - microlens >= 0.4 && < 0.5
      - QuickCheck >= 2.9 && < 2.12
      - tasty >= 0.10.1.2
      - tasty-hunit >= 0.9.2
      - tasty-quickcheck >= 0.8 && < 0.10
      - versions
