name: Build and Tests
on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Stack
        uses: mstksg/setup-stack@v1
      - name: Clone project
        uses: actions/checkout@v2
      - name: Build and run tests
        run: "stack test --fast --no-terminal"
